name: iProtector
author: LDX
version: 3.3.0
main: LDX\iProtector\Main
load: POSTWORLD
api: [5.0.0]
website: "https://github.com/LDX-MCPE/iProtector"
commands:
  area:
    description: "Allows you to manage areas."
    usage: "/area <create|delete|flag|here|list|pos1|pos2|tp|whitelist> [args: string]"
    permission: iprotector.command.area
permissions:
  iprotector.access:
    description: "Allows access to editing terrain in iProtector areas."
    default: op
  iprotector.command.area:
    description: "Allows access to the area command."
    default: op
  iprotector.command.area.create:
    description: "Allows access to the iProtector create subcommand."
    default: op
  iprotector.command.area.delete:
    description: "Allows access to the iProtector delete subcommand."
    default: op
  iprotector.command.area.flag:
    description: "Allows access to the iProtector flag subcommand."
    default: op
  iprotector.command.area.here:
    description: "Allows access to the iProtector here subcommand."
    default: op
  iprotector.command.area.list:
    description: "Allows access to the iProtector list subcommand."
    default: op
  iprotector.command.area.pos1:
    description: "Allows access to the iProtector pos1 subcommand."
    default: op
  iprotector.command.area.pos2:
    description: "Allows access to the iProtector pos2 subcommand."
    default: op
  iprotector.command.area.tp:
    description: "Allows access to the iProtector tp subcommand."
    default: op
  iprotector.command.area.whitelist:
    description: "Allows access to the iProtector whitelist subcommand."
    default: op
